// ------------------------------------------------------------------------------
// <auto-generated>
//     Sample EF6 EDMX designer file used by LegacyLens.NET static discovery.
//     This file is intentionally minimal and is not intended to be compiled.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace SampleLegacyApp.Data.LegacyCustomerModel;

// Static discovery signal for generated EDMX designer code.
internal static class LegacyCustomerModelDesignerMarker
{
    public const string ModelName = "LegacyCustomerModel";
}