// ------------------------------------------------------------------------------
// <auto-generated>
//     Sample EF6 EDMX generated context file used by LegacyLens.NET static discovery.
//     This file is intentionally minimal and is not intended to represent real EF code.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace SampleLegacyApp.Data.LegacyCustomerModel;

// These type names are deliberate static discovery signals for data-access and EDMX analysis.
// ObjectContext
// EntityObject
// EntityFramework
public sealed class LegacyCustomerEntities
{
    public string ContextName => "LegacyCustomerEntities";
}

public sealed class Customer
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? EmailAddress { get; set; }
}

public sealed class Order
{
    public int Id { get; set; }
    public int CustomerId { get; set; }
    public string OrderNumber { get; set; } = string.Empty;
}