using LegacyLens.Core.Analysis;
using LegacyLens.Core.Files;

namespace LegacyLens.Core.Tests.Analysis;

public sealed class CodeComplexityAnalyzerTests
{
    [Fact]
    public void Analyze_WhenFileInventoryIsNull_ThrowsArgumentNullException()
    {
        var analyzer = new CodeComplexityAnalyzer();

        var exception = Assert.Throws<ArgumentNullException>(() => analyzer.Analyze(null!));

        Assert.Equal("fileInventory", exception.ParamName);
    }

    [Fact]
    public void Analyze_EstimatesMemberComplexityFromDecisionSyntax()
    {
        var inventory = CreateInventory(
            "CustomerService.cs",
            """
            namespace Sample;

            public sealed class CustomerService
            {
                public string Classify(int value, bool other)
                {
                    if (value < 0)
                    {
                        return "negative";
                    }

                    if (value == 0 || other)
                    {
                        return "zero";
                    }

                    for (var i = 0; i < value; i++)
                    {
                        while (other)
                        {
                            break;
                        }
                    }

                    return value switch
                    {
                        > 10 when other => "large",
                        > 5 => "medium",
                        _ => "small"
                    };
                }
            }
            """);

        var report = new CodeComplexityAnalyzer().Analyze(inventory);

        var member = Assert.Single(report.Members);
        Assert.Equal("Sample.CustomerService", member.TypeName);
        Assert.Equal("Classify", member.MemberName);

        // Expected complexity:
        // Base method path = 1
        // if (value < 0) = +1
        // if (value == 0 || other) = +1
        // logical || = +1
        // for = +1
        // while = +1
        // switch expression arm: > 10 when other => "large" = +1
        // switch expression arm: > 5 => "medium" = +1
        // switch expression arm: _ => "small" = +1
        // pattern when guard = +1
        // Total = 10
        Assert.Equal(10, member.Complexity);
        Assert.Equal(CodeComplexitySeverity.Moderate, member.Severity);
        Assert.Equal(1, report.Summary.MemberCount);
        Assert.Equal(10, report.Summary.TotalComplexity);
    }

    [Fact]
    public void Analyze_AggregatesByTypeNamespaceProjectAndScanRoot()
    {
        var inventory = new ScanFileInventory(
            [
                CreateFile("Legacy.Web", "Controllers/HomeController.cs", """
                    namespace Legacy.Web.Controllers;

                    public sealed class HomeController
                    {
                        public void Index()
                        {
                        }

                        public void Save(bool valid)
                        {
                            if (valid)
                            {
                                return;
                            }
                        }
                    }
                    """),
                CreateFile("Legacy.Services", "CustomerService.cs", """
                    namespace Legacy.Services;

                    public sealed class CustomerService
                    {
                        public void Save(bool valid)
                        {
                            if (valid)
                            {
                                return;
                            }
                        }
                    }
                    """)
            ],
            [],
            [],
            [],
            []);

        var report = new CodeComplexityAnalyzer().Analyze(inventory);

        Assert.Equal(3, report.Summary.MemberCount);

        // Expected total:
        // HomeController.Index() = 1
        // HomeController.Save(bool) = 2
        // CustomerService.Save(bool) = 2
        // Total = 5
        Assert.Equal(5, report.Summary.TotalComplexity);

        Assert.Equal(2, report.TypeSummaries.Count);
        Assert.Equal(2, report.NamespaceSummaries.Count);
        Assert.Equal(2, report.ProjectSummaries.Count);
    }

    [Theory]
    [InlineData("LegacyModel.Designer.cs")]
    [InlineData("Customer.generated.cs")]
    [InlineData("Customer.g.cs")]
    public void Analyze_FlagsLikelyGeneratedFiles(string fileName)
    {
        var inventory = CreateInventory(
            fileName,
            """
            // <auto-generated>
            namespace Sample;

            public sealed class GeneratedCustomer
            {
                public void Execute()
                {
                }
            }
            """);

        var report = new CodeComplexityAnalyzer().Analyze(inventory);

        var member = Assert.Single(report.Members);
        Assert.True(member.IsLikelyGeneratedCode);
        Assert.Equal(1, report.Summary.GeneratedMemberCount);
    }

    private static ScanFileInventory CreateInventory(string fileName, string content)
    {
        return new ScanFileInventory(
            [CreateFile("Sample.Project", fileName, content)],
            [],
            [],
            [],
            []);
    }

    private static ScanFile CreateFile(string projectName, string relativePath, string content)
    {
        var root = Path.Combine(Path.GetTempPath(), "LegacyLens.CodeComplexityAnalyzerTests");
        var fullPath = Path.Combine(root, relativePath);

        return new ScanFile(
            projectName,
            Path.Combine(root, projectName, $"{projectName}.csproj"),
            Path.Combine(root, projectName),
            fullPath,
            relativePath,
            ".cs",
            content);
    }
}